import { Font, StyleSheet } from "@react-pdf/renderer";
import { kentBlue } from "@/theme/palette";

// 日本語フォント（M PLUS 1）
Font.register({
  family: "MPLUS1",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/mplus1/v15/R70EjygA28ymD4HgBUGzkN5Eyoj-WpW5VSa78g.ttf",
      fontWeight: 400,
    },
    {
      src: "https://fonts.gstatic.com/s/mplus1/v15/R70EjygA28ymD4HgBUGzkN5Eyoj-WpW5siG78g.ttf",
      fontWeight: 700,
    },
  ],
});

// フォールバック（〒 U+3012 など M PLUS 1 に無い文字用）
Font.register({
  family: "NotoSansJP",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/notosansjp/v55/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEj75s.ttf",
      fontWeight: 400,
    },
    {
      src: "https://fonts.gstatic.com/s/notosansjp/v55/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFPYk75s.ttf",
      fontWeight: 700,
    },
  ],
});

// ハイフネーション無効化（日本語対応。react-pdf#419）
Font.registerHyphenationCallback((word) => Array.from(word).flatMap((char) => [char, ""]));

// kent-blue（palette.ts と共有）
export const colors = {
  kentBlue50: kentBlue[50],
  kentBlue100: kentBlue[100],
  kentBlue200: kentBlue[200],
  kentBlue300: kentBlue[300],
  kentBlue400: kentBlue[400],
  kentBlue500: kentBlue[500],
  kentBlue600: kentBlue[600],
  kentBlue700: kentBlue[700],
  kentBlue800: kentBlue[800],
  kentBlue900: kentBlue[900],
  kentBlue950: kentBlue[950],
};

export const styles = StyleSheet.create({
  page: {
    fontFamily: "MPLUS1",
    fontSize: 9,
    paddingTop: 28,
    paddingBottom: 28,
    paddingHorizontal: 28,
    color: colors.kentBlue800,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 14,
    borderBottomWidth: 6,
    borderTopColor: colors.kentBlue500,
    borderBottomColor: colors.kentBlue500,
    paddingVertical: 9,
    paddingHorizontal: 9,
    marginBottom: 9,
  },
  headerTitle: { fontSize: 17, fontWeight: 700, color: colors.kentBlue800 },
  headerInfo: { alignItems: "flex-end" },
  headerInfoText: { fontSize: 8, color: colors.kentBlue800, textAlign: "right" },
  mainContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 18,
    paddingVertical: 9,
    paddingHorizontal: 9,
  },
  leftColumn: { flex: 1 },
  rightColumn: { width: 220 },
  customerSection: { marginBottom: 14 },
  customerName: { fontSize: 10, fontWeight: 700, color: colors.kentBlue800 },
  customerInfo: { fontSize: 9, color: colors.kentBlue800 },
  greetingSection: { marginBottom: 14 },
  greeting: { fontSize: 9, color: colors.kentBlue800 },
  doubleBoxWrapper: { position: "relative", padding: 3 },
  doubleBoxOuter: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 6,
    bottom: 6,
    borderWidth: 0.75,
    borderColor: colors.kentBlue400,
  },
  doubleBoxInner: {
    position: "absolute",
    top: 6,
    left: 6,
    right: 0,
    bottom: 0,
    borderWidth: 0.75,
    borderColor: colors.kentBlue300,
  },
  doubleBoxContent: { padding: 9, position: "relative" },
  amountRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "baseline",
    gap: 22,
    borderBottomWidth: 1.5,
    borderBottomColor: colors.kentBlue500,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  amountLabel: { fontSize: 11, color: colors.kentBlue800 },
  amountValue: { fontSize: 14, fontWeight: 700, color: colors.kentBlue800 },
  dueRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "baseline",
    gap: 22,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  dueLabel: { fontSize: 10, color: colors.kentBlue800 },
  dueValue: { fontSize: 10, fontWeight: 700, color: colors.kentBlue800 },
  companySection: { flexDirection: "row", gap: 4 },
  companyName: { fontSize: 10, fontWeight: 700, color: colors.kentBlue800 },
  companyInfo: { fontSize: 9, color: colors.kentBlue800 },
  registrationNumber: { fontSize: 9, color: colors.kentBlue800 },
  sealImage: { width: 60, height: 60 },
  bankBoxWrapper: { position: "relative", padding: 3, marginVertical: 7 },
  bankBoxContent: { padding: 9, position: "relative" },
  bankTitle: {
    fontSize: 10,
    fontWeight: 700,
    borderBottomWidth: 1.5,
    borderBottomColor: colors.kentBlue500,
    marginBottom: 4,
    color: colors.kentBlue800,
  },
  bankInfo: { fontSize: 9, color: colors.kentBlue800 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    borderBottomWidth: 1.5,
    borderBottomColor: colors.kentBlue500,
    paddingVertical: 7,
    marginBottom: 7,
    color: colors.kentBlue800,
  },
  table: { width: "100%" },
  tableHeader: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.kentBlue300,
  },
  tableHeaderCell: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    fontSize: 9,
    fontWeight: 700,
    textAlign: "center",
    color: colors.kentBlue800,
  },
  tableBody: { borderBottomWidth: 1, borderBottomColor: colors.kentBlue300 },
  tableRow: {
    flexDirection: "row",
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    borderColor: colors.kentBlue300,
  },
  tableCell: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    fontSize: 9,
    textAlign: "left",
    color: colors.kentBlue800,
  },
  tableCellRight: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    fontSize: 9,
    textAlign: "right",
    color: colors.kentBlue800,
  },
  tableCellCenter: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    fontSize: 9,
    textAlign: "center",
    color: colors.kentBlue800,
  },
  tableFooter: {
    alignItems: "center",
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.kentBlue300,
  },
  tableFooterCell: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    fontSize: 9,
    fontWeight: 700,
    textAlign: "left",
    color: colors.kentBlue800,
  },
  tableFooterValue: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    fontSize: 14,
    fontWeight: 700,
    textAlign: "right",
    color: colors.kentBlue800,
  },
  taxSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 18,
    paddingVertical: 9,
    marginHorizontal: 9,
    borderBottomWidth: 1.5,
    borderBottomColor: colors.kentBlue500,
  },
  taxTable: { flex: 1 },
  taxTableTitle: {
    fontSize: 9,
    fontWeight: 700,
    marginBottom: 4,
    color: colors.kentBlue800,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 18,
    paddingVertical: 9,
    paddingHorizontal: 9,
    borderBottomWidth: 14,
    borderBottomColor: colors.kentBlue500,
  },
  footerLeft: { flex: 1 },
  noteBoxWrapper: {
    position: "relative",
    padding: 3,
    marginVertical: 7,
    flex: 1,
  },
  noteBoxContent: { padding: 9, position: "relative" },
  noteTitle: {
    fontSize: 9,
    fontWeight: 700,
    borderBottomWidth: 1.5,
    borderBottomColor: colors.kentBlue500,
    marginBottom: 4,
    color: colors.kentBlue800,
  },
  noteText: { fontSize: 9, color: colors.kentBlue800 },
  detailSection: { paddingBottom: 9, paddingHorizontal: 9 },
});
